apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: f1
      defaultBucket: data
    secureJsonData:
      token: my-super-token
    isDefault: true
