{
 "title": "F1Race",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Race Control",
   "type": "table",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => r._measurement == \"race_control\")\n  |> filter(fn: (r) => r._field == \"message\") "
    }
   ]
  },
  {
   "title": "Lap Time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 5, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"lap_data\")\n  |> filter(fn: (r) => r._field == \"lap_time_sec\")\n  |> keep(columns: [\"_value\", \"_time\", \"driver\", \"year\", \"race\", \"session\"])\n"
    }
   ]
  },
  {
   "title": "Weather",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 5, "x": 14, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"weather\")\n  |> filter(fn: (r) => \n       r._field == \"air_temp\" or \n       r._field == \"track_temp\" or\n       r._field == \"humidity\"\n  )"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"weather\")\n  |> filter(fn: (r) => \n       r._field == \"wind_speed\"\n  )"
    }
   ]
  }
 ]
}