[project]
name = "f1-data-viewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "fastf1>=3.5.3",
    "influxdb-client>=1.48.0",
    "ruff>=0.11.8",
    "uvicorn>=0.34.2",
]
